mark-wiemer/ahkpp

src/providers/formattingProvider.ts, src/test/suite/format/format.test.ts, src/test/suite/format/samples/189-space-at-end-of-line.in.ahk, src/test/suite/format/samples/189-space-at-end-of-line.out.ahk
Closes #189.
-   trim original line after comment remove
-   concat comment with extra leading space
-   trim result string
---
=> Feature: Trim end of line

snippets/ahk.json
Closes #200.
Maybe it's bug in VS Code itself?
=> Fix: DriveSpaceFree snippet

snippets/ahk.json
From official documentation:
Specifying `#NoEnv` is recommended for all new scripts because:
1. It significantly improves performance whenever empty variables are used in an expression or command. It also improves DllCall's performance when unquoted parameter types are used (e.g. int vs. "int").
2. It prevents script bugs caused by environment variables whose names unexpectedly match variables used by the script.
3. AutoHotkey v2 will make this behavior the default.
Use `SetBatchLines, -1` to never sleep (i.e. have the script run at maximum speed). In AutoHotkey v2 is the default behaviour.
=> Update snippet #TEMPLATE

package.json, src/common/global.ts
-   assign settings in groups (for my new settings in other PRs, that are already in group 'formatter')
-   sort settings and `enum ConfigKey` in alphabet order
=> Refactor: assign settings in groups

package.json, src/common/global.ts, src/providers/formattingProvider.ts, src/providers/formattingProvider.utils.ts, src/test/suite/providers/formatting/formattingProvider.utils.test.ts
Closes #182.
Closes #197.
Closes #198.
- add new option
- delete leading empty lines in begin of file
formatter.allowedNumberOfEmptyLines = 2
```autohotkey
[empty line]
[empty line]
[empty line]
InputFile := "movie.mkv" 
InputFile = movie.mkv
```
```autohotkey
[empty line]
[empty line]
InputFile := "movie.mkv" 
InputFile = movie.mkv
```
```autohotkey
InputFile := "movie.mkv" 
InputFile = movie.mkv
```
=> Add option to extension's settings: "Allowed number of empty lines"

package.json, src/common/global.ts, src/providers/formattingProvider.ts, src/providers/formattingProvider.utils.ts, src/test/suite/providers/formatting/formattingProvider.utils.test.ts
Closes #187.
-   make trimming extra spaces between words optional
---
=> Add option to extension's settings: "Trim extra spaces between words"

package.json, src/common/codeUtil.ts, src/common/global.ts, src/providers/formattingProvider.ts, src/providers/formattingProvider.utils.ts, src/test/suite/providers/formatting/formattingProvider.utils.test.ts
-   preserve indentation on empty line
```autohotkey
foo() {
bar()
[4 spaces]
return
}
```
---
=> Add option to extension's settings: "Preserve indentation on empty line" 

Contributing.md
Inform contributors how to resolve a common issue when running tests. When switching branches, the TS tests would update but the JS tests that are executed wouldn't. Running `npm run pretest` solves this issue.
-   Closes #220 
---
=> Document contributing tests FAQ

package.json, src/common/global.ts, src/providers/formattingProvider.ts, src/providers/formattingProvider.types.ts, src/test/suite/format/format.test.ts, src/test/suite/format/samples/indent-code-after-label-false.in.ahk, src/test/suite/format/samples/indent-code-after-label-false.out.ahk, src/test/suite/format/samples/indent-code-after-label-true.in.ahk, src/test/suite/format/samples/indent-code-after-label-true.out.ahk
- new setting to disable indentation after label:
```autohotkey
;On
label:
MsgBox
return
;Off
label:
MsgBox
return
```
=> Add option to indent code after label

README.md
There are commands, that can produce indent on single next line. For example:
```autohotkey
if (true)
MsgBox
Loop % n
SoundBeep
```
Such code will be well formatted.
But do not nest such commands. The next code will be formatted incorrectly:
```autohotkey
if (true)
if (true)
MsgBox
Loop % n
if (true)
SoundBeep
```
Use their variants with braces:
```autohotkey
if (true) {
if (true)
MsgBox
}
Loop % n {
if (true)
SoundBeep
}
```
=> Add "Formatter Known Issues" section to README.md

src/providers/formattingProvider.ts, src/test/suite/format/format.test.ts, src/test/suite/format/samples/28-switch-case.in.ahk, src/test/suite/format/samples/28-switch-case.out.ahk, src/test/suite/format/samples/legacy-text-sharp-directive.in.ahk, src/test/suite/format/samples/legacy-text-sharp-directive.out.ahk, src/test/suite/format/samples/return-exit-exitapp.in.ahk, src/test/suite/format/samples/return-exit-exitapp.out.ahk
Closes #28.
Now it is possible to fix this error with a compromise: The `Return` command is placed at the same indentation level as the regular code within the special `Case:` and `Default:` labels. In this case `Return` don't belongs to `Case:` and `Default:` labels, it belongs to outer code (for example return from function, in which `Switch` used). Forcing `Return` to un-indent, as with regular `Label:`, brings unreadable "spaghetti" in the `formatterProvider.ts` code.
`Return` case:
```autohotkey
Switch SwitchValue {
Case CaseValue1:
Statements1
Return
Case CaseValue2a, CaseValue2b:
Statements2
Return
Default:
Statements3
Return
}
```
Regular case:
```autohotkey
Switch SwitchValue
{
Case CaseValue1:
Statements1
Case CaseValue2a, CaseValue2b: …
```
=> Fix Switch-Case Formatting

language/ahk.tmLanguage.yaml, src/test/suite/grammar/samples/54-double-colon-in-string.ahk, src/test/suite/grammar/samples/54-double-colon-in-string.ahk.snap
Strings with double colons in them are now highlighted correctly (GitHub may render incorrectly):
```ahk
Hotstring("::ykhis", "you know how it is")
Hotstring(":C:OOS", "out-of::-spec")
```
=> Fix syntax highlighting for strings with double-colons

.github/ISSUE_TEMPLATE/formatting-bug.md
-   remove "Unformatted input snippet" (reason: formatter trims all spaces and tabs around code, makes all code unformatted byself)
=> Remove "Unformatted input snippet"

language/snippets.json
- Add new function from AutoHotkey v1.1.36.0
- Update old functions
---
=> Fix&Update snippets

language/ahk.tmLanguage.yaml, src/test/suite/grammar/samples/69-if-directive.ahk, src/test/suite/grammar/samples/69-if-directive.ahk.snap, src/test/suite/grammar/samples/ahk-explorer.ahk.snap
Closes #69. Plus closes №70 in AHK+ [https://github.com/vscode-autohotkey/autohotkey-plus/issues/70](https://github.com/vscode-autohotkey/autohotkey-plus/issues/70)
- separate regex for `#If` directive
=> Grammar: #If directive highlight

.github/workflows/deploy.yml, .github/workflows/project-management.yml, docs/Development.md
From https://github.com/mark-wiemer/vscode-helloworld/blob/0.2.3/.github/workflows/deploy.yml
Closes #122.
=> Add auto-deployment

docs/Development.md, package-lock.json
- package-lock.json now reports correct version
- dev release docs now include "update package-lock" to fix this going forward
- no more detailed docs saying "run the tests" -- that's automated and implied
=> Fixup package lock and dev docs

src/providers/formattingProvider.ts, src/test/suite/format/format.test.ts, src/test/suite/format/samples/label-colon.in.ahk, src/test/suite/format/samples/label-colon.out.ahk
- label can't end with `::`
- name must have some characters, change quantifier `*` to `+`
=> Fix: label regexp

language/ahk.tmLanguage.yaml, language/snippets.json
Reverts vscode-autohotkey/ahkpp#336.
We shouldn't mix v1 and v2, we should approach this more holistically
=> Revert "Add HotIf directive from AHK v2"

language/ahk.tmLanguage.yaml, src/test/suite/grammar/samples/318-keyword-in-command.ahk, src/test/suite/grammar/samples/318-keyword-in-command.ahk.snap, src/test/suite/grammar/samples/ahk-explorer.ahk.snap
- add missing keywords
- add missing directives
=> Fix: keywords and direcives highlight

language/ahk.tmLanguage.yaml, src/test/suite/grammar/samples/295-command-comment.ahk.snap, src/test/suite/grammar/samples/295-function-call-comment.ahk.snap, src/test/suite/grammar/samples/318-keyword-in-command.ahk.snap, src/test/suite/grammar/samples/357-colon-comment.ahk, src/test/suite/grammar/samples/357-colon-comment.ahk.snap, src/test/suite/grammar/samples/ahk-explorer.ahk.snap
Closes #357.
- fix grammar regexp for hotkey
=> Fix: colon comment highlight

.vscode/launch.json, Changelog.md, demos/manualTests/formatting.ahk, package-lock.json, package.json
Closes #387, #384, #385.
-   `ahk++.file.interpreterPathV2` now defaults to `C:/Program Files/AutoHotkey/v2/AutoHotkey64.exe` ([Issue #387](https://github.com/mark-wiemer-org/ahkpp/issues/387))
-   Add breakpoint support for AHK v2 files ([Issue #384](https://github.com/mark-wiemer-org/ahkpp/issues/384))
-   Add AHK v2 debug config template ([#385](https://github.com/mark-wiemer-org/ahkpp/issues/385))
=> Add formatting test

Changelog.md, demos/manualTests/folding.ahk, demos/manualTests/formatting.ahk, demos/manualTests/hover.ahk, demos/manualTests/languageVersion/1.ahk, demos/manualTests/languageVersion/2.ahk, demos/v1Demo.ahk, demos/v2Demo.ahk2, package-lock.json, package.json, src/service/languageVersionService.ts
-   Fix language mode resetting when VS Code restarts ([Issue #392](https://github.com/mark-wiemer-org/ahkpp/issues/392))
=> v5.0.2 - Fix language mode resetting when VS Code restarts

Changelog.md
Closes #396.
-   Fix wrong claim about `.ahk` and `.ext` files defaulting to AHK v1
-   Add instructions for how to default to AHK v1
=> Update v5.0.0 changelog for default lang

Changelog.md, package.json, src/service/languageVersionService.ts
Closes #398.
-   Fix extension crash when switching to a nullish editor
=> Fix extension crash when switching to nullish editor

package-lock.json, package.json
- Address `npm audit` warnings by upgrading relevant packages
- Upgrade @vscode/test-electron to fix win32 archive issue (was occurring locally as well)
=> Fixup npm audit issues and pipeline failures

package.json, src/providers/format.test.ts, src/providers/formattingProvider.ts, src/providers/samples/432-label-inside-code-block.in.ahk, src/providers/samples/432-label-inside-code-block.out.ahk, src/providers/samples/ahk-explorer.out.ahk
Closes #432.
- make indent inside label only in top level code. No indent inside nested code blocks.
- change `ahk++.formatter.indentCodeAfterLabel` description in settings.
Indented code after `Hotkey` and `Label` needed only in top level hierarchy. Inside nested code blocks indent not needed. Optional behavior may be like in `Switch-Case` construction, where `Case CaseValue:` label has lower indent then code.
```autohotkey
Switch [SwitchValue]
{
Case CaseValue1: ; <-- lower indent
Statements1
Case CaseValue2a, CaseValue2b:
Statements2
Default:
Statements3
}
```
=> `FIX`: `label` inside code block breaks `return` indentation

src/providers/format.test.ts, src/providers/formattingProvider.ts, src/providers/samples/429-single-line-hotkey.in.ahk, src/providers/samples/429-single-line-hotkey.out.ahk
Closes #429.
- add special check for single-line hotkey
=> `FIX`: indent for single-line `hotkey` in fall-through scenario

src/parser/parser.test.ts, src/parser/parser.ts
Closes #438.
- remove space before colon in parser's regexp for label
=> `FIX`: don't show not valid `LABEL` in `OUTLINE`

src/providers/format.test.ts, src/providers/formattingProvider.ts, src/providers/samples/440-fall-through-single-line-hotkey-with-if-directive.in.ahk, src/providers/samples/440-fall-through-single-line-hotkey-with-if-directive.out.ahk, src/providers/samples/442-fall-through-single-line-hotkey-with-function.in.ahk, src/providers/samples/442-fall-through-single-line-hotkey-with-function.out.ahk
Closes #440.
Closes #442.
- another one cryptic change in formatter to fix regression in last bugfix
=> `FIX`: for #433 PR (single line hotkey fall-through scenario)

.github/workflows/deploy.yml, .github/workflows/project-management.yml
They haven't been pre-releases since 6.0.0! Sorry!
=> Fixup publish to Open VSX

changelog.md, package.json, readme.md
- Name is now `AHK++ (AutoHotkey Plus Plus)` as intended for 6.2.0
- GitHub releases linked in readme
- Changelog reflects name change in correct release now (GitHub releases updated as well)
=> Update display name, add GitHub download link, fix changelog

changelog.md, demos/manualTests/config.ahk2, package-lock.json, package.json, src/parser/parser.ts
-   Rewrite AutoHotkey v2 definition files using [GroggyOtter](https://github.com/GroggyOtter/ahkv2_definition_rewrite)'s syntaxes ([#521](https://github.com/mark-wiemer-org/ahkpp/issues/521))
-   Add exclude setting ([#488](https://github.com/mark-wiemer-org/ahkpp/issues/488))
-   Excluded files are not included in IntelliSense completion suggestions, even when they're added via `#include`
-   Changed `v2.exclude` setting to `exclude`
-   One setting works for both v1 and v2
-   Changes to this setting take effect immediately, no need to restart your IDE (different than thqby's extension)
-   v2 will exclude excluded files from suggestions even if they're opened in the IDE (different than thqby's extension)
-   v1 no longer automatically ignores files with `out`, `target`, or …
=> 6.3.0 - 2024-10-19 🕳️

.vscode/dev.code-snippets, changelog.md, src/common/codeUtil.ts, src/common/out.ts, src/parser/parser.ts, src/providers/defProvider.ts, src/providers/defProvider.utils.test.ts, src/providers/defProvider.utils.ts
Adds support for jumping to included files via ctrl+click.
Jumping to library functions not supported.
Works on #205.
=> Improve included method detection

changelog.md, language/language-configuration.json, package.json
-   Improve "go to definition" in v2 files ([thqby #610](https://github.com/thqby/vscode-autohotkey2-lsp/issues/610))
-   Improve environment variables when debugging via IDE for parity with running outside of IDE ([thqby #615](https://github.com/thqby/vscode-autohotkey2-lsp/issues/615))
-   Add hover tip for `switch` keyword in v2 files ([thqby #623](https://github.com/thqby/vscode-autohotkey2-lsp/issues/623))
=> Merge thqby 2.5.4

.github/ISSUE_TEMPLATE/bug-report--non-formatter-.md, changelog.md, demos/manualTests/bugfixes.ahk, demos/manualTests/config.ahk2, demos/manualTests/format/formatter.ahk1, docs/Troubleshooting.md, src/debugger/debugDispatcher.ts
To persist settings, we have to persist an entire object. That's why it wasn't working before. However, it doesn't seem trivial to fetch only the workspace config, we have to fetch the entire config (workspace, user, global). We don't know which properties came from which target by default, so for now we are pasting the entire config into workspace settings.
In the future, we could iterate through each property of the fetched object, find its configuration target (as ahk2/src/extension.ts already does), and only paste the workspace settings into, well, the workspace settings.
Quick pick fix is entirely in ahk2, other changes here are:
- changelog cleanup
- manual tests updates
- troubleshooting guide updates
- bug report template updates
=> Fix quick pick for "... does not exist" err, cleanup

changelog.md, demos/manualTests/commands.ahk2, demos/manualTests/config.ahk2, package-lock.json, package.json
-   Reduce required VS Code version to 1.68 (#574)
-   Update internal dependencies for security (#577)
=> v6.4.2 - 2024-12-16 🎄

.github/ISSUE_TEMPLATE/bug-report--non-formatter-.md
The old one is a dead link
-   Fixed link to point to correct location of troubleshooting docs
---
=> Fix troubleshooting guide link

changelog.md, docs/development.md, package-lock.json, package.json
-   Add [docs/debugging.md](./docs/debugging.md) and [docs/\_welcome.md](./docs/_welcome.md)
-   Fix `.vscode/launch.json` support for AHK v1 ([Issue #603](https://github.com/mark-wiemer/ahkpp/issues/603))
-   Add `.vscode/launch.json` support for AHK v2 ([PR #606](https://github.com/mark-wiemer/ahkpp/issues/603))
-   Change "AutoHotkey execute bin not found: ..." to "AutoHotkey interpreter not found" with a preceding message showing the interpreter path. ([PR #606](https://github.com/mark-wiemer/ahkpp/issues/603))
-   Remove the `runtime` argument from `launch.json` for both AHK v1 and AHK v2 due to issues with cross-version debugging ([PR #606](https://github.com/mark-wiemer/ahkpp/issues/603))
-   We are not considering this a breaking change as this behavior didn't work before. If …
=> 6.5.0 - 2025-02-23 💞

changelog.md, docs/glossary.md, docs/settings.md, package-lock.json, package.json
-   Improve extension performance when loading AHK v1 scripts ([PR #615](https://github.com/mark-wiemer/ahkpp/pull/615))
-   Change `Method` to `Function` in document symbols and internal references. This changes the document outline slightly, but should not change most theme icons and is more correct. ([PR #620](https://github.com/mark-wiemer/ahkpp/pull/620))
-   Have scripts referenced by `#include` bypass the `exclude` setting ([PR #623](https://github.com/mark-wiemer/ahkpp/pull/623))
-   Add experimental `funcDefSearch` setting that improves function definition resolution. For known issues, see [`settings.md`](./docs/settings.md). ([PR #623](https://github.com/mark-wiemer/ahkpp/pull/623))
=> 6.6.0 - 2025-03-21 🎩

changelog.md, package-lock.json, package.json
-   Add `AHK++ > General > logLevel` for logs in output channels ([#625](https://github.com/mark-wiemer/ahkpp/issues/625), [#635](https://github.com/mark-wiemer/ahkpp/issues/635))
=> 6.7.0 - 2025-04-01 🤡

changelog.md, src/common/log.ts
Closes #644.
-   Remove "Invalid setting" log if `logLevel` setting was not found
=> Remove "Invalid setting" log if `logLevel` setting was not found

changelog.md, src/common/utils.test.ts, src/common/utils.ts, src/parser/parser.ts
- Closes #641
- Closes #646
- Closes #649
-   Fix excessive logs when `#include` files aren't found by AHK++ ([#641](https://github.com/mark-wiemer/ahkpp/issues/641), [#646](https://github.com/mark-wiemer/ahkpp/issues/646), and [#649](https://github.com/mark-wiemer/ahkpp/issues/649))
-   Logic to detect these files has improved but still has at least one known issue: [#628](https://github.com/mark-wiemer/ahkpp/issues/628)
-   When a file isn't found, the log is now `debug` level instead of `warn` level to reduce noise
=> Improve resolveIncludedPaths logic

changelog.md, package-lock.json, package.json
-   Make "Configuration changed" log debug-level instead of info-level ([#625 (comment)](https://github.com/mark-wiemer/ahkpp/issues/625#issuecomment-2772599772))
-   Remove "Invalid setting" log if `logLevel` setting was not found ([#644](https://github.com/mark-wiemer/ahkpp/issues/644))
-   Fix excessive logs when `#include` files aren't found by AHK++ ([#641](https://github.com/mark-wiemer/ahkpp/issues/641), [#646](https://github.com/mark-wiemer/ahkpp/issues/646), [#649](https://github.com/mark-wiemer/ahkpp/issues/649), and [#657](https://github.com/mark-wiemer/ahkpp/issues/646))
-   Logic to detect these files has improved but still has at least one known issue: [#628](https://github.com/mark-wiemer/ahkpp/issues/628)
-   When a file isn't found, the log is now `debug` level instead of …
=> 6.7.1 - 2025-05-16 🎓
