mark-wiemer/ahkpp

- demos/demo_for_ahk_v1.ahk
- src/common/codeUtil.ts
- src/parser/parser.ts
- src/providers/formattingProvider.ts
Closes #18 .
- Improve documentation and variable naming
- Fix #18
---
> Fix formatting after conditional expression with string literals

- demos/demo_for_ahk_v2.ahk
- package-lock.json
- package.json
- src/debugger/struct/dbgpResponse.ts
- src/providers/ahkHoverProvider.ts
- tsconfig.json
- Some pre-release fixes. No feature changes or bugfixes.
---
> Hotfix 2.7.0

- snippets/ahk.json
> Resolve AHK+ conflicts

- src/test/suite/format/format.test.ts
- src/test/suite/providers/formatting/formattingProvider.utils.test.ts
- organize test data in array
- tidy up code
> refactor unit tests

- Contributing.md
- package.json
Closes #178 .
-   Only check *.ts files to unblock formatting PRs, like #159
-   Add `clean` to close #178
---
> Fixup package.json

- package.json
> Minor: Add missing dot in setting description

- snippets/ahk.json
Closes #209.
-  make command params identical to official docs
> Fix: snippets

- .github/workflows/codeql-analysis.yml
- .github/workflows/node.js.yml
- .github/workflows/project.yml
- package.json
Automatically move new issues and pull requests to project board
Closes #225
---
> Implement basic project management

- .github/workflows/project.yml
Old action didn't actually work, new action is created by GitHub actions so 🤞
---
> Fixup project management

- .github/workflows/project.yml
> Project management, take 3

- .github/workflows/project-management.yml
Silly Mark, read the docs and test with Hello World!
Working at https://github.com/mark-wiemer/vscode-helloworld/issues/39
---
> Use name of repo secret

- Changelog.md
- docs/Development.md
v3 includes a return of the much-awaited default debug icon!
> Fixup v3 changelog - default debug icon

- package.json
- src/extension.ts
- src/service/runnerService.ts
- src/test/suite/service/runnerService.test.ts
Closes #243.
Closes #253.
- new command `ahk++.compilerGui`
- new context menu `Compiler GUI`
> Compiler GUI

- syntaxes/ahk.tmLanguage.yaml
Accidentally removed in 6ce46e2
> Restore ahk.tmLanguage.yaml

- language/snippets.json
- syntaxes/ahk.tmLanguage.yaml
Closes #268.
- add missing directives, functions, commands
> Update snippets (AHK 1.1.33.00 and below)

- .github/workflows/project-management.yml
What a yucky acronym. It'll grow on me
> Add new issues to AHK4VSC project

- docs/TemplateSnippet.md
- package.json
- src/common/global.ts
- src/extension.ts
- src/service/templateService.ts
> Add template snippet name setting

- Changelog.md
- README.md
- New debug default keyboard shortcut
- Change to sentence case
- Add recent unreleased changes to changelog
> Update README and changelog

- language/ahk.tmLanguage.yaml
- src/test/suite/grammar/samples/86-import-comment.ahk
- src/test/suite/grammar/samples/86-import-comment.ahk.snap
> Fix include comment highlight

- src/providers/formattingProvider.ts
- src/test/suite/format/format.test.ts
- src/test/suite/format/samples/255-close-brace.in.ahk
- src/test/suite/format/samples/255-close-brace.out.ahk
> Fix close brace de-indent right after completed nested one command code

- Changelog.md
- Fixup links
- #303 not fully fixed, discussions ongoing
> Fixup changelog

- package-lock.json
- package.json
- src/debugger/debugDispatcher.ts
- src/debugger/debugServer.ts
- src/debugger/debugSession.ts
- src/debugger/handler/commandHandler.ts
Closes #279.
-   Revert untested debugger changes from v3.1.0 that introduced minor issue #279
> Revert debugger changes to fix #279

- src/debugger/debugDispatcher.ts
- src/service/runnerService.ts
Closes #134.
-   Debugger now connects to filenames with spaces properly
> Fix debugger issue with spaces in filenames

- language/ahk.tmLanguage.yaml
- language/snippets.json
Closes #116.
-   Recognize HotIf from AHK v2. If more v2 requests come in, we can look at pulling in all v2 values.
---
> Add HotIf directive from AHK v2

- .github/workflows/codeql-analysis.yml
- .github/workflows/node.js.yml
[Merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions)
> Run checks on merge enqueue

- package.json
- Note that parsing setting requires restart to take effect
- Add markdown to lists
> Improve settings descriptions

- package-lock.json
- package.json
- src/common/codeUtil.ts
- src/common/fileManager.ts
- src/common/global.ts
- src/common/out.ts
- src/debugger/debugSession.ts
- src/debugger/handler/commandHandler.ts
- src/debugger/handler/variableHandler.ts
- src/debugger/struct/dbgpResponse.ts
- src/parser/parser.ts
- src/providers/ahkHoverProvider.ts
- src/providers/defProvider.ts
- src/providers/symbolProvider.ts
- src/test/suite/common/codeUtil.test.ts
- tsconfig.json
Add type-checking to ensure future code is high quality
> Begin work for strict checks

- .vscode/launch.json
- Changelog.md
- demos/.vscode/launch.json
Reopens #385 
-   none really just changelog
> Remove support for AHK v2 debugger

- docs/TemplateSnippet.md
Fixes for #409
-   Update docs for snippets
> Clarify global snippets files are best

- language/snippetsV1.json
- update truncated PixelSearch snippet
> `FIX`: PixelSearch in snippetsV1

- Changelog.md
- package-lock.json
- package.json
-   Fix formatter in single line hotkey fall-through scenario ([#440](https://github.com/mark-wiemer-org/ahkpp/issues/440), [#442](https://github.com/mark-wiemer-org/ahkpp/issues/442))
-   Fix outline showing invalid labels ([#438](https://github.com/mark-wiemer-org/ahkpp/issues/438))
> 5.0.5 - 2024-05-24 🏝️

- readme.md
> Link main v1-v2 issue in readme

- Changelog.md
> Format changelog 5.0.0 entry

- .github/workflows/codeql-analysis.yml
> Use CodeQL v3

- .vscode/launch.json
- .vscode/tasks.json
- package.json
Accidentally removed in a recent PR
> Fix build for "Run Extension"

- Changelog.md
- demos/manualTests/help.ahk1
- src/service/helpService.ts
> Fix quick help on quoted strings

- Changelog.md
- language/ahk2.tmLanguage.yaml
- language/samples/0-v2-demo.ahk2.snap
- package-lock.json
- package.json
- package.nls.json
- package.nls.zh-cn.json
Progress on #478, not done yet, needs tests
> Merge thqby 2.5.2: Add "debug configs" command and more

- tsconfig.json
> Add compatibility with ahk2 unit tests

- .prettierignore
- package-lock.json
- package.json
Makes workspace management a bit easier
> Pin TypeScript to match ahk2-lsp submodule

- .github/workflows/deploy.yml
- package-lock.json
- package.json
-   Restore readme to marketplaces (lost due to [auto-publish error](https://github.com/mark-wiemer-org/ahkpp/actions/runs/11225795502/job/31205122158))
-   Update some dependencies to reduce risk of publishing errors in the future
> 6.2.1 - 2024-10-07 📚

- package.json
For the deploy script, I guess
> Wrap special chars in quotes

- package-lock.json
- package.json
-   Reduce extension size on marketplaces by ~100x (yes, really) ([#533](https://github.com/mark-wiemer-org/ahkpp/issues/533))
> 6.2.2 - 2024-10-07 🤏

- src/common/global.ts
- src/test/config.e2e.ts
- src/test/utils.ts
Working now, and we have automated tests to confirm it :)
Closes #528
> Test library suggestions setting

- changelog.md
- license.md
- readme.md
> Use GroggyOtter syntaxes

- .prettierignore
- package-lock.json
- package.json
Closes #574
https://code.visualstudio.com/updates/v1_68#_inline-completions-finalization
> Reduce requirement to VS Code 1.68

- changelog.md
> Fix IniWrite docs

- changelog.md
- docs/Development.md
- package-lock.json
- package.json
-   Fix IniWrite IntelliSense ([#590](https://github.com/mark-wiemer/ahkpp/issues/590))
-   Add [comprehensive settings reference](./docs/settings.md) in Markdown and improve docs within the settings editor ([#581](https://github.com/mark-wiemer/ahkpp/issues/581))
-   Update internal dependencies to Node 22, npm 11, and Mocha 11 to improve developer security and developer experience ([#583](https://github.com/mark-wiemer/ahkpp/pull/583))
> 6.4.3 - 2025-01-18 🎆

- docs/settings.md
Needed this for HTML, figured it might be good for AHK as well :)
> Add editor.quickSuggestions docs

- .gitignore
- changelog.md
- demos/manualTests/586-new-class-method.ahk2
> Add __New docs for all Object descendants

- demos/.vscode/launch.json
- demos/manualTests/debugger.ahk1
- demos/manualTests/debugger.ahk2
- src/service/runnerService.ts
Was defaulting to AHK v1 runtime
Ref #603
> Fix AHK v2 debug command

- changelog.md
Looks like a false positive :)
Ref #571
> Mark "set AHK v2 interpreter" as working

- changelog.md
Not sure where I went wrong there :/
> Clarify that 6.6.0 was all AHK v1

- changelog.md
> Update changelog to ref #205

- changelog.md
Ref https://github.com/mark-wiemer/ahkpp/issues/625#issuecomment-2772599772
> Make "config changed" debug-level

- docs/troubleshooting.md
> Add language version mismatch troubleshooting
